### ISSUE TITLE
Suggestion breaks interface

### ISSUE THREAD

**Issue by taeschnj** [mvdan/interfacer#22]
```
package main

import "fmt"

type StringerVar string

func (myx StringerVar) String() string {
	return string(myx)
}

type StringerInterface fmt.Stringer

type SomeInterface interface {
	FunctionA(StringerVar)
	FunctionB(StringerInterface) string
}

type SomeVar struct{}

func (i SomeVar) FunctionA(a StringerVar) {
	i.FunctionB(a)
}
func (i SomeVar) FunctionB(a StringerInterface) string {
	return a.String()
}

func main() {

	var somevar SomeInterface

	somevar = SomeVar{}
	somevar.FunctionA(StringerVar("hallo"))

}
```

interfacer suggests: `filename.go:20:28: a can be fmt.Stringer`
which would make 
`func (i SomeVar) FunctionA(a StringerVar) {`
to
`func (i SomeVar) FunctionA(a fmt.Stringer) {`
which makes line 31 (`	somevar = SomeVar{}`) invalid, since `SomeVar` no longer is implementing `FunctionA` correctly and thus it's not a `SomeInterface` anymore.

I thought this was fixed in #1 (or #2)

**Comment by mvdan** [comment]
Nice find! This is probably because I'm checking if the correct type is being used by name (e.g. comparing `fmt.Stringer` with `StringerVar`) instead of the type signatures. And I give the `std` packages more importance.

I should be comparing the signatures instead, which should fix this false positive. Thanks again for the feedback!

**Comment by mvdan** [comment]
The fix ended up being more subtle than I thought. Thanks for reporting!
